### ISSUE TITLE
Create flags to turn on/off modules

### ISSUE THREAD

**Issue by slsevilla** [CDCgov/phoenix#153]
# Description
- Expand flags in the `nextflow.config` to allow user control over which pipeline components are run

**Comment by slsevilla** [comment]
flags include:
- busco: 320cb64f1e824d5a7672fc513e13935af3ec9075
- ncbi_excel_creation: 47a0c5cf91ab185d2e40b990dcd676371cb2fe4b
- extended_qc: 47a0c5cf91ab185d2e40b990dcd676371cb2fe4b
- run_srst2_mlst
- run_griphin

**Comment by jvhagey** [comment]
If folks want to run BUSCO and/or SRST2 they can use the CDC_PHOENIX entry point. Griphin is a summary file so I don't see the value of turning that on/off. ncbi_excel_creation already has a [flag to turn it on or off](https://github.com/CDCgov/phoenix/blob/717d19c19338373fc0f89eba30757fe5cfb3e18a/workflows/phoenix.nf#L435) the default is to have it off. Granted the flag for this is a bit confusing because I have a layer of control that force it to be false if its not CDC_PHOENIX or the PHOENIX entry.
