### ISSUE TITLE
Missing hash.k2d file and "uncommitted changes"

### ISSUE THREAD

**Issue by DrB-S** [CDCgov/phoenix#41]
**Describe the bug**
Missing the hash.k2d file for the kraken2 db in .nextflow/assets/cdcgov/phoenix/assets/databases.

**Impact**
Received the "uncommitted changes" error.

**To Reproduce**
Running from the cloud:

nextflow run cdcgov/phoenix -r v1.0.0 -profile test,singularity -entry PHOENIX --kraken2db /data/Sequence_analysis/databases/kraken2_db/kraken2_phx
N E X T F L O W  ~  version 22.04.5
Project `cdcgov/phoenix` contains uncommitted changes -- Cannot switch to revision: v1.0.0

**Expected behavior**
Running program without error.

**Screenshots**

**Logs**
Sep-20 12:34:21.217 [main] DEBUG nextflow.cli.Launcher - $> nextflow run cdcgov/phoenix -r v1.0.0 -profile test,singularity -entry PHOENIX --kraken2db /data/Sequence_analysis/databases/kraken2_db/kraken2_phx
Sep-20 12:34:21.269 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 22.04.5
Sep-20 12:34:21.914 [main] DEBUG nextflow.scm.AssetManager - Git config: /app/becksts/.nextflow/assets/cdcgov/phoenix/.git/config; branch: master; remote: origin; url: https://github.com/CDCgov/phoenix.git
Sep-20 12:34:21.924 [main] DEBUG nextflow.scm.AssetManager - Git config: /app/becksts/.nextflow/assets/cdcgov/phoenix/.git/config; branch: master; remote: origin; url: https://github.com/CDCgov/phoenix.git
Sep-20 12:34:22.036 [main] DEBUG nextflow.cli.Launcher - Operation aborted
nextflow.exception.AbortOperationException: Project `cdcgov/phoenix` contains uncommitted changes -- Cannot switch to revision: v1.0.0
        at nextflow.scm.AssetManager.checkout(AssetManager.groovy:933)
        at nextflow.cli.CmdRun.getScriptFile0(CmdRun.groovy:489)
        at nextflow.cli.CmdRun.getScriptFile(CmdRun.groovy:415)
        at nextflow.cli.CmdRun.run(CmdRun.groovy:287)
        at nextflow.cli.Launcher.run(Launcher.groovy:480)
        at nextflow.cli.Launcher.main(Launcher.groovy:639)

**Additional context**
I noticed that the hash.k2d file is not found.

**Comment by jvhagey** [comment]
Hi @DrB-S, as a first pass this issue looks like the same described [here](https://github.com/CDCgov/phoenix/wiki/Troubleshooting#contains-uncommitted-changes). Can you run `rm -r ~/.nextflow/assets/cdcgov/phoenix`. When you run `nextflow run cdcgov/phoenix .....` it pulls a version and keeps it at ~/.nextflow/assets/cdcgov/phoenix` and it should be something similar on your end. The pipeline previously edited some files and in its base as it ran, but we realized it creates the problem you describe so we have since changed it to fix this from happening. Hopefully, deleting the older version you have and rerun will allow it to pull the fresh copy that contains this fix. An official release should be out at the end of the month just trying to confirm it runs on Terra/NF-Tower first. 

The hash.k2d file was never part of the PHoeNIx it has to be downloaded from our sharepoint site. Please email HAISeq@cdc.gov with the email address you would like the sharepoint link sent to. This file is too large to be include as part of PHoeNIx and needs to be passed to PHoeNIx in a folder that also contains the taxo.k2d and opts.k2d file with the `--kraken2db` argument. It seems that you are passing this argument though so make sure there is a full path for the folder and that it contains all three files. Let me know if this works.

**Comment by DrB-S** [comment]
Hi Jill,
I am _still waiting_ to receive the sharepoint link site via my email.  

I have once again deleted and rerun as you suggested, but I included the kraken2 path that is missing the hash.k2d file, so it errored out (see below).  I also installed Graphviz last week, but nextflow/phoenix is not finding it.

Errors:
Pipeline completed with errors-
WARN: To render the execution DAG in the required format it is required to install Graphviz -- See http://www.graphviz.org for more info.
Error executing process > 'PHOENIX:PHOENIX_EXTERNAL:KRAKEN2_TRIMD:KRAKEN2_TRIMD (Test_Sample)'

Caused by:
  Process `PHOENIX:PHOENIX_EXTERNAL:KRAKEN2_TRIMD:KRAKEN2_TRIMD (Test_Sample)` terminated with an error exit status (2)

Command executed:

  kraken2 \
      --db kraken2_phx \
      --threads 2 \
      --report Test_Sample.kraken2_trimd.report.txt \
      --gzip-compressed \
      --unclassified-out Test_Sample.unclassified#.fastq \
      --classified-out Test_Sample.classified#.fastq \
      --output Test_Sample.kraken2_trimd.classifiedreads.txt \
      --paired \
      --use-names  \
      Test_Sample_1.trim.fastq.gz Test_Sample_2.trim.fastq.gz

  gzip *.fastq

  cat <<-END_VERSIONS > versions.yml
  "PHOENIX:PHOENIX_EXTERNAL:KRAKEN2_TRIMD:KRAKEN2_TRIMD":
      kraken2: $(echo $(kraken2 --version 2>&1) | sed 's/^.*Kraken version //; s/ .*$//')
  END_VERSIONS

Command exit status:
  2

Command output:
  (empty)

Command error:
  kraken2: database ("./kraken2_phx") does not contain necessary file hash.k2d

Work dir:
  /data/Sequence_analysis/PHoeNIx/Analyses/work/d5/2c91553ee9f8a070a5d3472af3f7f6

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

Thanks,
Steve

**Comment by jvhagey** [comment]
Since you were able to get this to work by passing the full path to the PHoeNIx with the `--kraken2db` argument I am going to close this issue. Thanks for trying out PHoeNIx!
